name: Production - Cloud functions CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:
      - name: Initialize Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build Docker image
        run: docker build . -t kaiz/cloud-run-test

      - name: Push Docker image
        run: gcloud builds submit --tag gcr.io/pathforge-v1/kaiz/cloud-run-test .

      - name: Deploy
        run: |-
          gcloud run deploy cloud-run-test --image gcr.io/pathforge-v1/kaiz/cloud-run-test --port=80 --allow-unauthenticated --region=asia-southeast1 --platform=managed